services:
  # Nginx setup for lava proivder
  nginx:
    image: nginx:latest
    # networks:
    #   - lava_network
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./nginx/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    # depends_on:
    #   - lava-provider
    # restart: always
  #Init service to create account for the provider
  lava-provider-init:
    image: ghcr.io/lavanet/lava/lavap:${LAVAP_VERSION:-latest}
    container_name: lava-provider-init
    volumes:
      - lava_data:/lava
    environment:
      - PROVIDER_WALLET=${PROVIDER_WALLET:-servicer1}
      - KEYRING_BACKEND=${KEYRING_BACKEND:-test}
    entrypoint: ["lavap"]
    command: 
      - "keys"
      - "add"
      - "${PROVIDER_WALLET:-servicer1}"
      - "--keyring-backend"
      - "${KEYRING_BACKEND:-test}"
    restart: "no"
  
  lava-provider:
    image: ghcr.io/lavanet/lava/lavap:${LAVAP_VERSION:-latest}
    depends_on:
      lava-provider-init:
        condition: service_completed_successfully
    volumes:
      - ../common/provider.yml:/lava/config/provider.yml:ro
      - lava_data:/lava
    environment:
      - TZ=UTC
      - PROVIDER_WALLET=${PROVIDER_WALLET:-servicer1}
      - GEOLOCATION=${GEOLOCATION:-2}
      - CHAIN_ID=${CHAIN_ID:-lava-testnet-2}
      - KEYRING_BACKEND=${KEYRING_BACKEND:-test}
      - LAVA_RPC_NODE=${LAVA_RPC_NODE:-https://public-rpc.lavanet.xyz:443/rpc/}
    command:
      [
        "rpcprovider",
        "provider.yml",
        "--chain-id",
        "${CHAIN_ID:-lava-testnet-2}",
        "--from",
        "${PROVIDER_WALLET:-servicer1}",
        "--log_level",
        "debug",
        "--geolocation",
        "${GEOLOCATION:-2}",
        "--keyring-backend",
        "${KEYRING_BACKEND:-test}",
        "--node",
        "${LAVA_RPC_NODE:-https://public-rpc.lavanet.xyz:443/rpc/}",
      ]
    # Expose the provider port directly since there's no nginx
    ports:
      - "${PROVIDER_SUI_PORT:-443}:${PROVIDER_SUI_PORT:-443}"  # Use the same port of the provider
    restart: always

    

volumes:
  lava_data:
    driver: local